name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Python ${{ matrix.python-version }} (torch=${{ matrix.torch }})
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        torch: ["none", "cpu"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install PyTorch (CPU)
        if: matrix.torch == 'cpu'
        run: |
          python -m pip install --extra-index-url https://download.pytorch.org/whl/cpu torch
      - name: Install package + test deps (no torch)
        if: matrix.torch == 'none'
        run: |
          pip install -e .[ase]
          pip install pytest
      - name: Install package + test deps (with torch)
        if: matrix.torch == 'cpu'
        run: |
          pip install -e .[ase,torch]
          pip install pytest
      - name: Run tests
        run: pytest -q
